#!/usr/bin/env bash
# wrapper script for waybar with args, see https://github.com/swaywm/sway/issues/5724

TOUCHPAD_ID="$(swaymsg -t get_inputs | grep 'identifier.*Touchpad' | cut -d '"' -f4)" #give me the touchpad identifier

echo "$TOUCHPAD_ID"

STATE="$(swaymsg -t get_inputs | jq '.[] | select(.identifier=="'"$TOUCHPAD_ID"'") | .libinput.send_events')" #check if touchpad is enabled

[ "$STATE" = '"enabled"' ] && swaymsg input "$TOUCHPAD_ID" events disabled || swaymsg input "$TOUCHPAD_ID" events enabled
